/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  EasingType,
} from 'easing-animation-frames';


export namespace Components {

  interface ProgressRing {
    'decimalSize': number;
    'disableDigits': boolean;
    'duration': number;
    'easingType': EasingType;
    /**
    * Text
    */
    'intSize': number;
    /**
    * Colors
    */
    'invertColors': boolean;
    /**
    * Animation
    */
    'percent': number;
    /**
    * Shape
    */
    'radius': number;
    'strokeWidth': number;
  }
  interface ProgressRingAttributes extends StencilHTMLAttributes {
    'decimalSize'?: number;
    'disableDigits'?: boolean;
    'duration'?: number;
    'easingType'?: EasingType;
    /**
    * Text
    */
    'intSize'?: number;
    /**
    * Colors
    */
    'invertColors'?: boolean;
    /**
    * Animation
    */
    'percent'?: number;
    /**
    * Shape
    */
    'radius'?: number;
    'strokeWidth'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ProgressRing': Components.ProgressRing;
  }

  interface StencilIntrinsicElements {
    'progress-ring': Components.ProgressRingAttributes;
  }


  interface HTMLProgressRingElement extends Components.ProgressRing, HTMLStencilElement {}
  var HTMLProgressRingElement: {
    prototype: HTMLProgressRingElement;
    new (): HTMLProgressRingElement;
  };

  interface HTMLElementTagNameMap {
    'progress-ring': HTMLProgressRingElement
  }

  interface ElementTagNameMap {
    'progress-ring': HTMLProgressRingElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
