/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EasingType } from "easing-animation-frames";
export namespace Components {
    interface ProgressRing {
        "decimalSize": number;
        "disableDecimals": boolean;
        "disableDigits": boolean;
        "duration": number;
        "easingType": EasingType;
        /**
          * Text
         */
        "intSize": number;
        /**
          * Colors
         */
        "invertColors": boolean;
        /**
          * Animation
         */
        "percentage": number;
        /**
          * Shape
         */
        "radius": number;
        /**
          * Style
         */
        "roundLinecap": boolean;
        "strokeWidth": number;
    }
}
declare global {
    interface HTMLProgressRingElement extends Components.ProgressRing, HTMLStencilElement {
    }
    var HTMLProgressRingElement: {
        prototype: HTMLProgressRingElement;
        new (): HTMLProgressRingElement;
    };
    interface HTMLElementTagNameMap {
        "progress-ring": HTMLProgressRingElement;
    }
}
declare namespace LocalJSX {
    interface ProgressRing {
        "decimalSize"?: number;
        "disableDecimals"?: boolean;
        "disableDigits"?: boolean;
        "duration"?: number;
        "easingType"?: EasingType;
        /**
          * Text
         */
        "intSize"?: number;
        /**
          * Colors
         */
        "invertColors"?: boolean;
        /**
          * Animation
         */
        "percentage"?: number;
        /**
          * Shape
         */
        "radius"?: number;
        /**
          * Style
         */
        "roundLinecap"?: boolean;
        "strokeWidth"?: number;
    }
    interface IntrinsicElements {
        "progress-ring": ProgressRing;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "progress-ring": LocalJSX.ProgressRing & JSXBase.HTMLAttributes<HTMLProgressRingElement>;
        }
    }
}
